# Based on:  https://stackoverflow.com/a/73882805
name: minify

on:
  push:
    branches:
      - 'main'
    paths:
      - index.html 

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install CLI tools
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: sudo apt-get install minify
      - run: minify -o docs/index.html index.html
      
      # Push changes to `gh-pages` branch
      - run: |
          git config --global user.name 'Action'
          git config --global user.email 'action@users.noreply.github.com'
          git add docs/index.html
          git commit -am "minify action"
          git push
